table DeviceHealth

	column DeviceId
		dataType: string
		sourceColumn: DeviceId

	column DeviceName
		dataType: string
		sourceColumn: DeviceName

	column DeviceType
		dataType: string
		sourceColumn: DeviceType

	column MachineGroup
		dataType: string
		sourceColumn: MachineGroup

	column DupDeviceId
		dataType: string
		sourceColumn: DupDeviceId

	column DeviceTags
		dataType: string
		sourceColumn: DeviceTags

	column CloudPlatforms
		dataType: string
		sourceColumn: CloudPlatforms

	column CloudLocation
		dataType: string
		sourceColumn: CloudLocation

	column ADDomain
		dataType: string
		sourceColumn: ADDomain

	column IsVDI
		dataType: string
		sourceColumn: IsVDI

	column ManagedBy
		dataType: string
		sourceColumn: ManagedBy

	column ManagementMethods
		dataType: string
		sourceColumn: ManagementMethods

	column OnboardingStatus
		dataType: string
		sourceColumn: OnboardingStatus

	column SensorHealthState
		dataType: string
		sourceColumn: SensorHealthState

	column ConnectivityType
		dataType: string
		sourceColumn: ConnectivityType

	column ExposureLevel
		dataType: string
		sourceColumn: ExposureLevel

	column MigrationStatus
		dataType: string
		sourceColumn: MigrationStatus

	column TrendAgentPresent
		dataType: int64
		sourceColumn: TrendAgentPresent

	column TrendInstalled
		dataType: string
		sourceColumn: TrendInstalled

	column TrendProduct
		dataType: string
		sourceColumn: TrendProduct

	column ThirdPartyAV
		dataType: string
		sourceColumn: ThirdPartyAV

	column ThirdPartyEDR
		dataType: string
		sourceColumn: ThirdPartyEDR

	column DeviceStatus
		dataType: string
		sourceColumn: DeviceStatus

	column LastSeen
		dataType: dateTime
		sourceColumn: LastSeen
		formatString: General Date

	column OSPlatform
		dataType: string
		sourceColumn: OSPlatform

	column OSDistribution
		dataType: string
		sourceColumn: OSDistribution

	column OSVersionInfo
		dataType: string
		sourceColumn: OSVersionInfo

	column OSBuildVersion
		dataType: string
		sourceColumn: OSBuildVersion

	column OSLatestVer
		dataType: string
		sourceColumn: OSLatestVer

	column OSUpdated
		dataType: string
		sourceColumn: OSUpdated

	column EOS
		dataType: dateTime
		sourceColumn: EOS
		formatString: General Date

	column EDRVersion
		dataType: string
		sourceColumn: EDRVersion

	column EDRLatestVersion
		dataType: string
		sourceColumn: EDRLatestVersion

	column EDRUpdate
		dataType: string
		sourceColumn: EDRUpdate

	column EDRImpairedCommunications
		dataType: string
		sourceColumn: EDRImpairedCommunications

	column EDRSensorDataCollection
		dataType: string
		sourceColumn: EDRSensorDataCollection

	column AVProductVersion
		dataType: string
		sourceColumn: AVProductVersion

	column AVPlatformCompliant
		dataType: string
		sourceColumn: AVPlatformCompliant

	column AVEngineVersion
		dataType: string
		sourceColumn: AVEngineVersion

	column AVEngineCompliant
		dataType: string
		sourceColumn: AVEngineCompliant

	column AVSigVersion
		dataType: string
		sourceColumn: AVSigVersion

	column AVSigCompliant
		dataType: string
		sourceColumn: AVSigCompliant

	column SensorCompliant
		dataType: string
		sourceColumn: SensorCompliant

	column AVSigLastUpdateTime
		dataType: dateTime
		sourceColumn: AVSigLastUpdateTime
		formatString: General Date

	column AVMode
		dataType: string
		sourceColumn: AVMode

	column AntivirusEnabled
		dataType: string
		sourceColumn: AntivirusEnabled

	column AntivirusReporting
		dataType: string
		sourceColumn: AntivirusReporting

	column RealtimeProtection
		dataType: string
		sourceColumn: RealtimeProtection

	column CloudProtection
		dataType: string
		sourceColumn: CloudProtection

	column BehaviorMonitoring
		dataType: string
		sourceColumn: BehaviorMonitoring

	column NetworkProtection
		dataType: string
		sourceColumn: NetworkProtection

	column PUAProtection
		dataType: string
		sourceColumn: PUAProtection

	column TamperProtection
		dataType: string
		sourceColumn: TamperProtection

	column EBPFStatus
		dataType: string
		sourceColumn: EBPFStatus

	column MobileMgmt
		dataType: string
		sourceColumn: MobileMgmt

	column EnrollmentProfile
		dataType: string
		sourceColumn: EnrollmentProfile

	column DefenderAppVersion
		dataType: string
		sourceColumn: DefenderAppVersion

	column AppCompliant
		dataType: string
		sourceColumn: AppCompliant

	column WebProtection
		dataType: string
		sourceColumn: WebProtection

	column Healthy
		dataType: string
		sourceColumn: Healthy

	column SensorConnectivity
		dataType: string
		sourceColumn: SensorConnectivity

	column ConfigState = IF(DeviceHealth[OnboardingStatus]<>"Onboarded", "Not onboarded (backlog)", IF(DeviceHealth[TrendInstalled]="No" && DeviceHealth[Healthy]="Healthy", "Fully migrated & configured", "Onboarded - needs attention"))
		dataType: string

	column 'Platform State' = SWITCH(DeviceHealth[AVPlatformCompliant], "GOOD", "Up to date", "WARN", "Behind", "BAD", "Out of date", "N/A")
		dataType: string

	column 'Platform State Color' = SWITCH(DeviceHealth[AVPlatformCompliant], "GOOD", "#107C10", "WARN", "#F7A500", "BAD", "#D13438", "#8A8886")
		dataType: string

	column 'Sensor State' = SWITCH(DeviceHealth[SensorCompliant], "GOOD", "Up to date", "WARN", "Behind", "BAD", "Out of date", "UNSUPPORTED", "Unsupported OS", "N/A")
		dataType: string

	column 'Sensor State Color' = SWITCH(DeviceHealth[SensorCompliant], "GOOD", "#107C10", "WARN", "#F7A500", "BAD", "#D13438", "UNSUPPORTED", "#605E5C", "#8A8886")
		dataType: string

	column 'Version State' = VAR w = IF(DeviceHealth[AVPlatformCompliant]="BAD" || DeviceHealth[SensorCompliant]="BAD", 3, IF(DeviceHealth[AVPlatformCompliant]="WARN" || DeviceHealth[SensorCompliant]="WARN", 2, IF(DeviceHealth[AVPlatformCompliant]="GOOD" || DeviceHealth[SensorCompliant]="GOOD", 1, 0))) RETURN SWITCH(w, 3, "Out of date", 2, "Behind", 1, "Up to date", "N/A")
		dataType: string

	column 'Version State Color' = VAR w = IF(DeviceHealth[AVPlatformCompliant]="BAD" || DeviceHealth[SensorCompliant]="BAD", 3, IF(DeviceHealth[AVPlatformCompliant]="WARN" || DeviceHealth[SensorCompliant]="WARN", 2, IF(DeviceHealth[AVPlatformCompliant]="GOOD" || DeviceHealth[SensorCompliant]="GOOD", 1, 0))) RETURN SWITCH(w, 3, "#D13438", 2, "#F7A500", 1, "#107C10", "#8A8886")
		dataType: string

	column 'App State' = SWITCH(DeviceHealth[AppCompliant], "GOOD", "Up to date", "WARN", "Behind", "BAD", "Out of date", "N/A")
		dataType: string

	column 'App State Color' = SWITCH(DeviceHealth[AppCompliant], "GOOD", "#107C10", "WARN", "#F7A500", "BAD", "#D13438", "#8A8886")
		dataType: string

	column 'Web Protection Color' = SWITCH(DeviceHealth[WebProtection], "GOOD", "#107C10", "BAD", "#D13438", "#8A8886")
		dataType: string

	column 'Sensor Connectivity State' = SWITCH(DeviceHealth[SensorConnectivity], "GOOD", "Active", "WARN", "Impaired - monitor", "BAD", "Not reporting", "N/A")
		dataType: string

	column 'Sensor Connectivity Color' = SWITCH(DeviceHealth[SensorConnectivity], "GOOD", "#107C10", "WARN", "#F7A500", "BAD", "#D13438", "#8A8886")
		dataType: string

	measure 'Total Devices' = COUNTROWS(DeviceHealth) + 0
		formatString: 0

	measure 'Clients' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[DeviceType]="Client")
		formatString: 0

	measure 'Servers' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[DeviceType]="Server")
		formatString: 0

	measure 'Active Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[DeviceStatus]="Active", DeviceHealth[OnboardingStatus]="Onboarded") + 0
		formatString: 0

	measure 'Stale Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[DeviceStatus]="Stale", DeviceHealth[OnboardingStatus]="Onboarded") + 0
		formatString: 0

	measure 'MDE Onboarded' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[MigrationStatus]="MDE onboarded") + 0
		formatString: 0

	measure 'Trend Remaining' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[MigrationStatus]<>"MDE onboarded") + 0
		formatString: 0

	measure 'Migration %' = IF([Trend Source Devices] = 0, "N/A", DIVIDE([Healthy Onboarded Devices], [Trend Source Devices]))
		formatString: 0.0%

	measure 'Healthy Onboarded Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[OnboardingStatus]="Onboarded", DeviceHealth[Healthy]="Healthy") + 0
		formatString: 0

	measure 'MDE Onboarding Coverage %' = DIVIDE([MDE Onboarded], [Total Devices], 0)
		formatString: 0.0%

	measure 'Onboarded Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[OnboardingStatus]="Onboarded")
		formatString: 0

	measure 'AV Sig Compliant %' = VAR _den = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVSigCompliant]<>"N/A") RETURN IF(_den=0, "N/A", DIVIDE(CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVSigCompliant]="GOOD"), _den))
		formatString: 0.0%

	measure 'AV Engine Compliant %' = VAR _den = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVEngineCompliant]<>"N/A") RETURN IF(_den=0, "N/A", DIVIDE(CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVEngineCompliant]="GOOD"), _den))
		formatString: 0.0%

	measure 'Platform Compliant %' = VAR _den = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVPlatformCompliant]<>"N/A") RETURN IF(_den=0, "N/A", DIVIDE(CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVPlatformCompliant]="GOOD"), _den))
		formatString: 0.0%

	measure 'Sensor Compliant %' = VAR _den = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorCompliant]<>"N/A") RETURN IF(_den=0, "N/A", DIVIDE(CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorCompliant]="GOOD"), _den))
		formatString: 0.0%

	measure 'Non-Compliant Devices' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[AVSigCompliant]="BAD" || DeviceHealth[AVEngineCompliant]="BAD" || DeviceHealth[AVPlatformCompliant]="BAD" || DeviceHealth[SensorCompliant]="BAD"))
		formatString: 0

	measure 'Fully Migrated & Configured' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[OnboardingStatus]="Onboarded" && DeviceHealth[TrendInstalled]="No" && DeviceHealth[Healthy]="Healthy"))
		formatString: 0

	measure 'Fully Migrated & Configured %' = DIVIDE([Fully Migrated & Configured], [Total Devices], 0)
		formatString: 0.0%

	measure 'Needs Attention' = [Onboarded Devices] - [Fully Migrated & Configured] + 0
		formatString: 0

	measure 'Migration Backlog' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[OnboardingStatus]="Can be onboarded")
		formatString: 0

	measure 'Healthy Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[Healthy]="Healthy") + 0
		formatString: 0

	measure 'Healthy %' = DIVIDE([Healthy Devices], [Onboarded Devices], 0)
		formatString: 0.0%

	measure 'Trend Installed Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[TrendInstalled]="Yes")
		formatString: 0

	measure 'VDI Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[IsVDI]="Yes")
		formatString: 0

	measure 'Platform Up To Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVPlatformCompliant]="GOOD")
		formatString: 0

	measure 'Platform Behind' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVPlatformCompliant]="WARN")
		formatString: 0

	measure 'Platform Out Of Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVPlatformCompliant]="BAD")
		formatString: 0

	measure 'AV Sig Up To Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVSigCompliant]="GOOD") + 0
		formatString: 0

	measure 'AV Sig Behind' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVSigCompliant]="WARN") + 0
		formatString: 0

	measure 'AV Sig Out Of Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVSigCompliant]="BAD") + 0
		formatString: 0

	measure 'Sensor Up To Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorCompliant]="GOOD")
		formatString: 0

	measure 'Sensor Behind' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorCompliant]="WARN")
		formatString: 0

	measure 'Sensor Out Of Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorCompliant]="BAD")
		formatString: 0

	measure 'Not On Latest Version' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[AVPlatformCompliant]="WARN" || DeviceHealth[AVPlatformCompliant]="BAD" || DeviceHealth[SensorCompliant]="WARN" || DeviceHealth[SensorCompliant]="BAD"))
		formatString: 0

	measure 'Not On Latest %' = DIVIDE([Not On Latest Version], [Onboarded Devices], 0)
		formatString: 0.0%

	measure 'Sensor Active' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorConnectivity]="GOOD")
		formatString: 0

	measure 'Sensor Impaired' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorConnectivity]="WARN")
		formatString: 0

	measure 'Sensor Not Reporting' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[SensorConnectivity]="BAD")
		formatString: 0

	measure 'Sensor Needs Attention' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[SensorConnectivity]="WARN" || DeviceHealth[SensorConnectivity]="BAD"))
		formatString: 0

	measure 'Mobile Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[DeviceType]="Mobile") + 0
		formatString: 0

	measure 'Android Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[OSPlatform]="Android")
		formatString: 0

	measure 'iOS Devices' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[OSPlatform]="iOS")
		formatString: 0

	measure 'Mobile Onboarded' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[DeviceType]="Mobile", DeviceHealth[OnboardingStatus]="Onboarded") + 0
		formatString: 0

	measure 'Mobile MDM Enrolled' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[MobileMgmt]="MDM (Intune)") + 0
		formatString: 0

	measure 'Mobile MAM Enrolled' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[MobileMgmt]="MAM (App Protection)") + 0
		formatString: 0

	measure 'Mobile Unmanaged' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[DeviceType]="Mobile" && DeviceHealth[MobileMgmt]="Unmanaged"))
		formatString: 0

	measure 'Mobile App Out Of Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AppCompliant]="BAD")
		formatString: 0

	measure 'Mobile App Behind' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AppCompliant]="WARN")
		formatString: 0

	measure 'Mobile App Up To Date' = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AppCompliant]="GOOD")
		formatString: 0

	measure 'Mobile Web Protection Off' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[DeviceType]="Mobile" && DeviceHealth[WebProtection]="BAD"))
		formatString: 0

	measure 'Mobile Stale' = CALCULATE(COUNTROWS(DeviceHealth), FILTER(DeviceHealth, DeviceHealth[DeviceType]="Mobile" && DeviceHealth[DeviceStatus]="Stale"))
		formatString: 0

	measure 'Fully Migrated' = [Fully Migrated & Configured] + 0
		formatString: 0

	measure 'Fully Migrated %' = [Fully Migrated & Configured %]
		formatString: 0.0%

	measure 'AV Sig %' = [AV Sig Compliant %]
		formatString: 0.0%

	measure 'AV Engine %' = [AV Engine Compliant %]
		formatString: 0.0%

	measure 'Platform %' = [Platform Compliant %]
		formatString: 0.0%

	measure 'Sensor %' = [Sensor Compliant %]
		formatString: 0.0%

	measure 'Non-Compliant' = [Non-Compliant Devices] + 0
		formatString: 0

	measure 'Sensor Attention' = [Sensor Needs Attention] + 0
		formatString: 0

	measure 'Not Reporting' = [Sensor Not Reporting] + 0
		formatString: 0

	measure 'Platform Outdated' = VAR _g = CALCULATE(COUNTROWS(DeviceHealth), DeviceHealth[AVPlatformCompliant]<>"N/A") RETURN IF(_g=0, "N/A", [Platform Out Of Date] + 0)
		formatString: 0

	measure 'Sensor Outdated' = [Sensor Out Of Date] + 0
		formatString: 0

	measure 'Android' = [Android Devices] + 0
		formatString: 0

	measure 'iOS' = [iOS Devices] + 0
		formatString: 0

	measure 'MDM Enrolled' = [Mobile MDM Enrolled] + 0
		formatString: 0

	measure 'MAM Enrolled' = [Mobile MAM Enrolled] + 0
		formatString: 0

	measure 'App Outdated' = [Mobile App Out Of Date] + 0
		formatString: 0

	partition DeviceHealth = m
		mode: import
		source =
				let
				    // ------------------------------------------------------------------
				    // Defender for Endpoint EXPORT-ASSESSMENT data path (v3.0.0).
				    // Replaces the single advanced-hunting runHuntingQuery (capped at
				    // 10,000 rows) with the paged export APIs so the model scales to
				    // 100k+ devices. All three sources are same-host + @odata.nextLink
				    // paged, so scheduled refresh stays valid (static base URL).
				    //   List machines                            (Machine.Read.All)
				    //   SecureConfigurationsAssessmentByMachine  (Vulnerability.Read.All)
				    //   SoftwareInventoryByMachine               (Software.Read.All)
				    // Authentication: Anonymous datasource + an app-only (client-credentials)
				    // token minted here in Power Query using the OAuth2 app registration
				    // (Tenant/Client/Secret injected at deploy time). Power BI managed
				    // Service Principal is NOT usable for these REST APIs: it cannot resolve
				    // the token audience for graph.microsoft.com, and Web.Contents POST bodies
				    // (used by the advanced-hunting trend query) are only permitted under
				    // Anonymous auth (Mashup 10347). Anonymous + a self-supplied Authorization
				    // header is the durable, refresh-safe pattern and mints a fresh token
				    // every refresh (no 1-hour expiry problem).
				    // Authentication: the api.securitycenter.microsoft.com datasource is bound
				    // in Power BI with a Service Principal (app-only OAuth2 client credentials).
				    // Power BI mints and attaches the bearer token itself, so there is NO token
				    // request in this query and NO second data source. A single-data-source
				    // query sidesteps the Power Query data-combination firewall entirely, which
				    // is mandatory for scheduled refresh under a PBIP/TMDL model (the Desktop
				    // "ignore privacy levels" fast-combine setting has no TMDL equivalent, so a
				    // token minted in-query would break refresh with "Unable to combine data").
				    // The SP needs application permissions Machine.Read.All, Vulnerability.Read.All
				    // and Software.Read.All (admin-consented) on WindowsDefenderATP.
				    // Fields only available via the gateway-only InfoGathering "via files"
				    // export (AV mode / rings / exact AV versions / platform+engine
				    // currency) are surfaced as "N/A" here by design (cloud-only build).
				    // ------------------------------------------------------------------
				    // Refresh-safe paged GET: the base URL is a string LITERAL in every
				    // Web.Contents call so the datasource identity is stable across refreshes.
				    PageAll = (relPath as text) as list =>
				        let
				            Fetch = (q as record) =>
				                let
				                    r = Json.Document(Web.Contents("https://api.securitycenter.microsoft.com/api",
				                          [ RelativePath = relPath, Query = q ])),
				                    vals = r[value],
				                    nextLink = try r[#"@odata.nextLink"] otherwise null,
				                    nextQ = if nextLink = null then null else Uri.Parts(nextLink)[Query]
				                in
				                    [ v = vals, q = nextQ ],
				            pages = List.Generate(
				                () => Fetch([ pageSize = "50000" ]),
				                each _ <> null,
				                each if [q] = null then null else Fetch([q]),
				                each [v]),
				            combined = List.Combine(pages)
				        in
				            combined,
				    Machines0 = PageAll("machines"),
				    SecCfg    = PageAll("machines/SecureConfigurationsAssessmentByMachine"),
				    Software  = PageAll("machines/SoftwareInventoryByMachine"),
				    // ---- helpers -----------------------------------------------------
				    F = (r, n, d) => Record.FieldOrDefault(r, n, d),
				    Lower = (v) => Text.Lower(if v = null then "" else Text.From(v)),
				    // Fixed-width, zero-padded, comparable version key (text, avoids the
				    // 2^53 double-precision limit that a numeric key would hit).
				    VerKey = (v) as text =>
				        let s = if v = null then "" else Text.From(v),
				            p = Text.Split(s, "."),
				            seg = (i) => let d = if i < List.Count(p) then Text.Select(p{i}, {"0".."9"}) else "" in Text.PadStart(if d = "" then "0" else d, 7, "0")
				        in Text.Combine(List.Transform({0,1,2,3}, seg), ""),
				    IsLinTxt = (osp) => let o = Lower(osp) in Text.Contains(o, "linux") or List.Contains({"ubuntu","debian","rhel","centos","suse","amazon","oracle","fedora","sles","rocky","alma"}, Text.Trim(o)) or List.AnyTrue(List.Transform({"ubuntu","debian","rhel","centos","suse","amazon linux","oracle linux"}, each Text.Contains(o, _))),
				    // ---- secure-config scid -> Test mapping (same taxonomy as v2.x) ---
				    ScidMap = [
				        #"scid-2000"="EDRSensorEnabled", #"scid-2001"="SensorDataCollectionWin", #"scid-5001"="SensorDataCollectionMac", #"scid-6001"="SensorDataCollectionLin",
				        #"scid-2002"="ImpairedCommunicationsWin", #"scid-5002"="ImpairedCommunicationsMac", #"scid-6002"="ImpairedCommunicationsLin",
				        #"scid-2003"="TamperProtectionWin", #"scid-5092"="TamperProtectionMac",
				        #"scid-2010"="AntivirusEnabled", #"scid-2011"="AntivirusSignatureVersionWin", #"scid-5095"="AntivirusSignatureVersionMac", #"scid-6095"="AntivirusSignatureVersionLin",
				        #"scid-2012"="RealtimeProtectionWin", #"scid-5090"="RealtimeProtectionMac", #"scid-6090"="RealtimeProtectionLin",
				        #"scid-91"="BehaviorMonitoring", #"scid-2013"="PUAProtectionWin", #"scid-5091"="PUAProtectionMac", #"scid-6091"="PUAProtectionLin",
				        #"scid-2014"="AntivirusReporting", #"scid-2016"="CloudProtectionWin", #"scid-5094"="CloudProtectionMac", #"scid-6094"="CloudProtectionLin",
				        #"scid-2030"="EDRUpdate1", #"scid-96"="NetworkProtection"
				    ],
				    CfgRecs = List.Transform(SecCfg, (r) =>
				        let t = Record.FieldOrDefault(ScidMap, F(r, "configurationId", ""), null) in
				        if t = null then null
				        else [ did = F(r, "deviceId", null), test = t,
				               res = if F(r, "isApplicable", true) = false then "N/A" else if F(r, "isCompliant", false) = true then "GOOD" else "BAD" ]),
				    CfgTab = Table.FromRecords(List.RemoveNulls(CfgRecs), type table [did = text, test = text, res = text]),
				    CfgGrp = if Table.RowCount(CfgTab) = 0 then #table({"did","bag"}, {}) else Table.Group(CfgTab, {"did"}, {{"bag", each try Record.FromList([res], [test]) otherwise []}}),
				    BagLk = if Table.RowCount(CfgGrp) = 0 then [] else Record.FromList(CfgGrp[bag], CfgGrp[did]),
				    // ---- software inventory -> per-device classification -------------
				    TrendMarks = {"apex one","officescan","deep security","worry-free","serverprotect","endpoint sensor","security agent","cloud one"},
				    IsTrend = (s) => Text.Contains(s, "trend") or List.AnyTrue(List.Transform(TrendMarks, each Text.Contains(s, _))),
				    MgmtTool = (s) =>
				        if Text.Contains(s, "intune") then "Intune"
				        else if Text.Contains(s, "configuration manager") then "Configuration Manager"
				        else if Text.Contains(s, "connected machine agent") or Text.Contains(s, "azcmagent") then "Microsoft Defender for Cloud (Arc)"
				        else null,
				    AVName = (s) =>
				        if Text.Contains(s, "trend") or Text.Contains(s, "apex one") or Text.Contains(s, "officescan") or Text.Contains(s, "deep security") then "Trend Micro"
				        else if Text.Contains(s, "sophos") or Text.Contains(s, "intercept x") then "Sophos"
				        else if Text.Contains(s, "trellix") or Text.Contains(s, "mcafee") then "McAfee / Trellix"
				        else if Text.Contains(s, "symantec") or Text.Contains(s, "norton") then "Symantec"
				        else if Text.Contains(s, "kaspersky") then "Kaspersky"
				        else if Text.Contains(s, "eset") or Text.Contains(s, "nod32") then "ESET"
				        else if Text.Contains(s, "bitdefender") or Text.Contains(s, "gravityzone") then "Bitdefender"
				        else if Text.Contains(s, "sentinelone") or Text.Contains(s, "sentinel one") then "SentinelOne"
				        else if Text.Contains(s, "crowdstrike") or Text.Contains(s, "falcon") then "CrowdStrike"
				        else if Text.Contains(s, "carbon black") or Text.Contains(s, "cylance") then "Other 3rd-party"
				        else null,
				    EDRName = (s) =>
				        if Text.Contains(s, "crowdstrike") or Text.Contains(s, "falcon") then "CrowdStrike Falcon"
				        else if Text.Contains(s, "sentinelone") or Text.Contains(s, "sentinel one") or Text.Contains(s, "singularity") then "SentinelOne"
				        else if Text.Contains(s, "carbon black") or Text.Contains(s, "cb defense") then "VMware Carbon Black"
				        else if Text.Contains(s, "cortex") or Text.Contains(s, "traps") then "Palo Alto Cortex XDR"
				        else if Text.Contains(s, "cybereason") then "Cybereason"
				        else if Text.Contains(s, "tanium") then "Tanium"
				        else if Text.Contains(s, "cylance") then "BlackBerry Cylance"
				        else null,
				    SwRecs = List.Transform(Software, (r) =>
				        [ did = F(r, "deviceId", null),
				          sw = Lower((F(r, "softwareVendor", "") ?? "") & " " & (F(r, "softwareName", "") ?? "")),
				          nm = Text.From(F(r, "softwareName", "") ?? ""),
				          eos = F(r, "endOfSupportDate", null) ]),
				    SwTab = Table.FromRecords(SwRecs, type table [did = text, sw = text, nm = text, eos = any]),
				    SwGrp = if Table.RowCount(SwTab) = 0 then #table({"did","TrendInstalled","TrendProduct","MgmtTools","ThirdPartyAV","ThirdPartyEDR","EOS"}, {}) else Table.Group(SwTab, {"did"}, {
				        {"TrendInstalled", each if List.AnyTrue(List.Transform([sw], IsTrend)) then "Yes" else "No"},
				        {"TrendProduct", each Text.Combine(List.Distinct(List.Transform(Table.SelectRows(_, each IsTrend([sw]))[nm], each _)), " , ")},
				        {"MgmtTools", each Text.Combine(List.Distinct(List.RemoveNulls(List.Transform([sw], MgmtTool))), ", ")},
				        {"ThirdPartyAV", each let a = List.RemoveNulls(List.Transform([sw], AVName)) in if List.Count(a) > 0 then a{0} else "None"},
				        {"ThirdPartyEDR", each let a = List.RemoveNulls(List.Transform([sw], EDRName)) in if List.Count(a) > 0 then a{0} else "None"},
				        {"EOS", each List.Min(List.RemoveNulls([eos]))}
				    }),
				    SwLk = if Table.RowCount(SwGrp) = 0 then [] else Record.FromList(Table.ToRecords(SwGrp), SwGrp[did]),
				    // ---- device inventory (List machines) ----------------------------
				    // Iterate the raw list directly (records have heterogeneous optional
				    // fields, so Table.FromRecords over the raw payload is unsafe). A
				    // uniform normalized projection is used only for the baseline groups.
				    // [noise filter v3.6] Optional removed-device cutoff: drop devices whose lastSeen is
				    // older than RemovedAfterDaysCutoff days. 0 = keep all (default). The deploy script
				    // rewrites this literal from -RemovedAfterDays / config.removedAfterDays when set.
				    RemovedAfterDaysCutoff = 0,
				    CutoffUtc = if RemovedAfterDaysCutoff <= 0 then null else DateTime.From(DateTimeZone.UtcNow()) - #duration(RemovedAfterDaysCutoff, 0, 0, 0),
				    KeepRecent = (m) => CutoffUtc = null or (let ls = F(m, "lastSeen", null) in ls = null or (try DateTime.From(ls) >= CutoffUtc otherwise true)),
				    MachActiveList = List.Select(Machines0, each F(_, "mergedIntoMachineId", null) = null and F(_, "isExcluded", false) <> true and KeepRecent(_)),
				    MachNorm = List.Transform(MachActiveList, each [ osPlatform = Text.From(F(_, "osPlatform", "") ?? ""), version = Text.From(F(_, "version", "") ?? ""), agentVersion = F(_, "agentVersion", null), onb = Text.From(F(_, "onboardingStatus", "") ?? "") ]),
				    MachNormTab = if List.Count(MachNorm) = 0 then #table({"osPlatform","version","agentVersion","onb"}, {}) else Table.FromRecords(MachNorm),
				    // ---- fleet-relative EDR sensor baseline (per OSPlatform|version) --
				    OnbV = Table.SelectRows(MachNormTab, each [onb] = "Onboarded" and [agentVersion] <> null),
				    OnbV2 = Table.AddColumn(OnbV, "gk", each [osPlatform] & "|" & [version]),
				    OnbV3 = Table.AddColumn(OnbV2, "vk", each VerKey([agentVersion])),
				    SGrp = if Table.RowCount(OnbV3) = 0 then #table({"gk","green","red"}, {}) else Table.Group(OnbV3, {"gk"}, {
				        {"green", each List.Max([vk])},
				        {"red", each let s = List.Sort(List.Distinct([vk]), Order.Descending), lin = List.AnyTrue(List.Transform([osPlatform], each IsLinTxt(_))), rank = if lin then 9 else 2 in if List.Count(s) > rank then s{rank} else null}
				    }),
				    SGreen = if Table.RowCount(SGrp) = 0 then [] else Record.FromList(SGrp[green], SGrp[gk]),
				    SRed = if Table.RowCount(SGrp) = 0 then [] else Record.FromList(SGrp[red], SGrp[gk]),
				    // ---- fleet-relative OS baseline (per OSPlatform) ------------------
				    OnbO = Table.SelectRows(MachNormTab, each [onb] = "Onboarded" and [version] <> null and [version] <> ""),
				    OnbO2 = Table.AddColumn(OnbO, "ok", each [osPlatform]),
				    OnbO3 = Table.AddColumn(OnbO2, "ov", each VerKey([version])),
				    OGrp = if Table.RowCount(OnbO3) = 0 then #table({"ok","ogreen"}, {}) else Table.Group(OnbO3, {"ok"}, {{"ogreen", each List.Max([ov])}}),
				    OGreen = if Table.RowCount(OGrp) = 0 then [] else Record.FromList(OGrp[ogreen], OGrp[ok]),
				    // ---- AV posture seed (advanced hunting, deploy-time) -------------
				    // AV mode / exact platform+engine+signature versions and their fleet-
				    // relative currency (GOOD/WARN/BAD per OS build, Win/Linux/mac) are only
				    // in DeviceTvmInfoGathering, which the cloud export APIs above do not
				    // carry. The deploy script runs deploy/assets/DeviceAvPosture.kql against
				    // the advanced-hunting REST API and embeds one record per DeviceId below
				    // as base64 JSON (__AVPOSTURE_SEED_B64__), regenerated on every (re)deploy
				    // (same rationale as DeploymentTrend: advanced hunting is POST-only and
				    // cannot run during a cloud scheduled refresh). Missing/failed seed -> the
				    // try falls back to an empty lookup and every AV field stays "N/A".
				    AvSeed = try Json.Document(Binary.FromText("__AVPOSTURE_SEED_B64__", BinaryEncoding.Base64)) otherwise {},
				    AvLk = if List.Count(AvSeed) = 0 then [] else Record.FromList(AvSeed, List.Transform(AvSeed, each Text.From(Record.FieldOrDefault(_, "DeviceId", "")))),
				    // ---- per-device projection to the DeviceHealth schema ------------
				    NowUtc = DateTime.From(DateTimeZone.UtcNow()),
				    Build = (m) =>
				        let
				            did = F(m, "id", null),
				            avp = Record.FieldOrDefault(AvLk, did, null),
				            avf = (fld) => if avp = null then null else let v = Record.FieldOrDefault(avp, fld, null) in if v = null or v = "" then null else v,
				            name = Text.From(F(m, "computerDnsName", "") ?? ""),
				            osp = Text.From(F(m, "osPlatform", "") ?? ""),
				            oLow = Lower(osp),
				            ver = Text.From(F(m, "version", "") ?? ""),
				            onbRaw = F(m, "onboardingStatus", ""),
				            onb = onbRaw = "Onboarded",
				            onbLow = Lower(onbRaw),
				            onbLabel = if onb then "Onboarded" else if Text.Contains(onbLow, "unsupported") then "Unsupported" else if Text.Contains(onbLow, "insufficient") then "Insufficient info" else "Can be onboarded",
				            isMobile = List.Contains({"android","ios"}, oLow),
				            win = Text.StartsWith(oLow, "windows"),
				            mac = Text.Contains(oLow, "mac"),
				            devType = if isMobile then "Mobile" else if win and Text.Contains(oLow, "server") then "Server" else if win then "Client" else if mac then "Client" else "Server",
				            bag = Record.FieldOrDefault(BagLk, did, []),
				            pick = (a, b, c) => if win then Record.FieldOrDefault(bag, a, "N/A") else if mac then Record.FieldOrDefault(bag, b, "N/A") else Record.FieldOrDefault(bag, c, "N/A"),
				            RTP = pick("RealtimeProtectionWin","RealtimeProtectionMac","RealtimeProtectionLin"),
				            PUA = pick("PUAProtectionWin","PUAProtectionMac","PUAProtectionLin"),
				            CLOUD = pick("CloudProtectionWin","CloudProtectionMac","CloudProtectionLin"),
				            TAMP = if win then Record.FieldOrDefault(bag,"TamperProtectionWin","N/A") else if mac then Record.FieldOrDefault(bag,"TamperProtectionMac","N/A") else "N/A",
				            SDC = pick("SensorDataCollectionWin","SensorDataCollectionMac","SensorDataCollectionLin"),
				            IMP = pick("ImpairedCommunicationsWin","ImpairedCommunicationsMac","ImpairedCommunicationsLin"),
				            AVSIG = pick("AntivirusSignatureVersionWin","AntivirusSignatureVersionMac","AntivirusSignatureVersionLin"),
				            BM = Record.FieldOrDefault(bag, "BehaviorMonitoring", "N/A"),
				            NP = Record.FieldOrDefault(bag, "NetworkProtection", "N/A"),
				            AVEN = Record.FieldOrDefault(bag, "AntivirusEnabled", "N/A"),
				            AVREP = Record.FieldOrDefault(bag, "AntivirusReporting", "N/A"),
				            sw = Record.FieldOrDefault(SwLk, did, null),
				            trendInst = if sw = null then "No" else F(sw, "TrendInstalled", "No"),
				            eosDate = if sw = null then null else F(sw, "EOS", null),
				            gk = osp & "|" & ver,
				            vk = if F(m, "agentVersion", null) = null then null else VerKey(F(m, "agentVersion", "")),
				            sGreen = Record.FieldOrDefault(SGreen, gk, null),
				            sRed = Record.FieldOrDefault(SRed, gk, null),
				            sensor = if not onb then "N/A" else if vk = null or sGreen = null then "N/A" else if vk >= sGreen then "GOOD" else if sRed <> null and vk <= sRed then "BAD" else "WARN",
				            health = Text.From(F(m, "healthStatus", "") ?? ""),
				            hLow = Lower(health),
				            conn = if not onb then "N/A" else if hLow = "active" then "GOOD" else if Text.Contains(hLow, "impair") then "WARN" else if List.Contains({"inactive","nosensordata","misconfigured"}, hLow) then "BAD" else "WARN",
				            oGreen = Record.FieldOrDefault(OGreen, osp, null),
				            ovk = if ver = "" then null else VerKey(ver),
				            eosPast = eosDate <> null and (try DateTime.From(eosDate) < NowUtc otherwise false),
				            osUpd = if not onb then "N/A" else if eosPast then "UNSUPPORTED" else if ovk = null or oGreen = null then "N/A" else if ovk >= oGreen then "GOOD" else "WARN",
				            bad = (x) => x = "BAD" or x = "UNSUPPORTED",
				            healthy = if not onb then "N/A - not onboarded" else if List.AnyTrue(List.Transform({AVSIG, sensor, RTP, CLOUD, BM, TAMP, NP, IMP, SDC, AVEN, AVREP, conn, osUpd}, bad)) then "Unhealthy" else "Healthy",
				            grp = let g = F(m, "rbacGroupName", null) in if g = null or g = "" then "Unassigned" else g,
				            tags = F(m, "machineTags", {}),
				            tagTxt = if tags = null or List.Count(tags) = 0 then "Untagged" else Text.Combine(List.Transform(tags, each Text.From(_)), " "),
				            vmMeta = F(m, "vmMetadata", null),
				            cloudProv = if vmMeta = null then "" else Text.From(F(vmMeta, "cloudProvider", "") ?? ""),
				            cloudLoc = if Text.Contains(Lower(cloudProv), "azure") then "Azure" else if Text.Contains(Lower(cloudProv), "aws") or Text.Contains(Lower(cloudProv), "amazon") then "AWS" else if Text.Contains(Lower(cloudProv), "gcp") or Text.Contains(Lower(cloudProv), "google") then "GCP" else if cloudProv = "" then "On-premises" else cloudProv,
				            mgBy = Text.From(F(m, "managedBy", "") ?? ""),
				            managedBy = if mgBy = "MicrosoftDefenderForEndpoint" then "Microsoft Defender for Endpoint" else if Text.Contains(mgBy, "Intune") then "Intune" else if Text.Contains(mgBy, "ConfigurationManager") or mgBy = "Sccm" then "Configuration Manager" else if onb then "Microsoft Defender for Endpoint" else "Unmanaged",
				            mgMethods = if sw = null or F(sw, "MgmtTools", "") = "" then "<None>" else F(sw, "MgmtTools", "<None>"),
				            lastSeen = F(m, "lastSeen", null),
				            devStatus = if lastSeen <> null and (try DateTime.From(lastSeen) > NowUtc - #duration(7,0,0,0) otherwise false) then "Active" else "Stale",
				            edrVerFull = Text.From(F(m, "agentVersion", "") ?? ""),
				            edrVer = let p = Text.Split(edrVerFull, ".") in if List.Count(p) >= 2 then p{0} & "." & p{1} else edrVerFull,
				            edrLatest = if sGreen = null then "" else edrVer,
				            adDomain = if Text.Contains(name, ".") then Text.Range(name, Text.PositionOf(name, ".") + 1) else "Azure AD joined / Workgroup",
				            migStatus = if onb and trendInst = "Yes" then "Co-existence" else if onb then "MDE onboarded" else if trendInst = "Yes" then "Trend only" else "Not onboarded"
				        in
				            [ DeviceId = did, DeviceName = name, DeviceType = devType, MachineGroup = grp,
				              DupDeviceId = if F(m, "isPotentialDuplication", false) = true then "Yes" else "No",
				              DeviceTags = tagTxt, CloudPlatforms = cloudProv, CloudLocation = cloudLoc, ADDomain = adDomain,
				              IsVDI = if Text.Contains(Lower(tagTxt), "vdi") or Text.Contains(Lower(tagTxt), "nonpersistent") then "Yes" else "No",
				              ManagedBy = managedBy, ManagementMethods = mgMethods,
				              OnboardingStatus = onbLabel,
				              SensorHealthState = health, ConnectivityType = "N/A", ExposureLevel = Text.From(F(m, "exposureLevel", "") ?? ""),
				              MigrationStatus = migStatus, TrendInstalled = trendInst,
				              TrendProduct = if sw = null then "" else F(sw, "TrendProduct", ""),
				              ThirdPartyAV = if sw = null then "None" else F(sw, "ThirdPartyAV", "None"),
				              ThirdPartyEDR = if sw = null then "None" else F(sw, "ThirdPartyEDR", "None"),
				              DeviceStatus = devStatus, LastSeen = lastSeen,
				              OSPlatform = osp, OSDistribution = Text.Trim(osp & " " & ver), OSVersionInfo = ver,
				              OSBuildVersion = ver, OSLatestVer = "", OSUpdated = osUpd, EOS = eosDate,
				              EDRVersion = edrVer, EDRLatestVersion = edrLatest, EDRUpdate = sensor,
				              EDRImpairedCommunications = IMP, EDRSensorDataCollection = SDC,
				              AVProductVersion = avf("AVProductVersion") ?? "N/A", AVPlatformCompliant = avf("AVPlatformCompliant") ?? "N/A", AVEngineVersion = avf("AVEngineVersion") ?? "N/A", AVEngineCompliant = avf("AVEngineCompliant") ?? "N/A",
				              AVSigVersion = avf("AVSigVersion") ?? "N/A", AVSigCompliant = avf("AVSigCompliant") ?? AVSIG, SensorCompliant = sensor, AVSigLastUpdateTime = avf("AVSigLastUpdateTime"),
				              AVMode = avf("AVMode") ?? "N/A", AntivirusEnabled = AVEN, AntivirusReporting = AVREP,
				              RealtimeProtection = RTP, CloudProtection = CLOUD, BehaviorMonitoring = BM,
				              NetworkProtection = NP, PUAProtection = PUA, TamperProtection = TAMP, EBPFStatus = avf("EBPFStatus") ?? "N/A",
				              MobileMgmt = if isMobile then (if managedBy = "Intune" then "MDM (Intune)" else if managedBy = "Unmanaged" then "Unmanaged" else "Unknown") else "N/A",
				              EnrollmentProfile = "N/A", DefenderAppVersion = if isMobile then edrVerFull else "",
				              AppCompliant = if isMobile then sensor else "N/A", WebProtection = if isMobile then "Unknown" else "N/A",
				              Healthy = healthy, SensorConnectivity = conn ],
				    Rows = List.Transform(MachActiveList, Build),
				    AsTable = Table.FromRecords(Rows, {"DeviceId", "DeviceName", "DeviceType", "MachineGroup", "DupDeviceId", "DeviceTags", "CloudPlatforms", "CloudLocation", "ADDomain", "IsVDI", "ManagedBy", "ManagementMethods", "OnboardingStatus", "SensorHealthState", "ConnectivityType", "ExposureLevel", "MigrationStatus", "TrendInstalled", "TrendProduct", "ThirdPartyAV", "ThirdPartyEDR", "DeviceStatus", "LastSeen", "OSPlatform", "OSDistribution", "OSVersionInfo", "OSBuildVersion", "OSLatestVer", "OSUpdated", "EOS", "EDRVersion", "EDRLatestVersion", "EDRUpdate", "EDRImpairedCommunications", "EDRSensorDataCollection", "AVProductVersion", "AVPlatformCompliant", "AVEngineVersion", "AVEngineCompliant", "AVSigVersion", "AVSigCompliant", "SensorCompliant", "AVSigLastUpdateTime", "AVMode", "AntivirusEnabled", "AntivirusReporting", "RealtimeProtection", "CloudProtection", "BehaviorMonitoring", "NetworkProtection", "PUAProtection", "TamperProtection", "EBPFStatus", "MobileMgmt", "EnrollmentProfile", "DefenderAppVersion", "AppCompliant", "WebProtection", "Healthy", "SensorConnectivity"}, MissingField.UseNull),
				    WithTrendPresent = Table.AddColumn(AsTable, "TrendAgentPresent", each if [TrendInstalled] = "Yes" then 1 else 0, Int64.Type),
				    Dated = Table.TransformColumns(WithTrendPresent, {{"LastSeen", each if _ = null or _ = "" or _ = "N/A" then null else Date.FromText(Text.Start(Text.From(_),10)), type date}, {"EOS", each if _ = null or _ = "" or _ = "N/A" then null else Date.FromText(Text.Start(Text.From(_),10)), type date}, {"AVSigLastUpdateTime", each if _ = null or _ = "" or _ = "N/A" then null else Date.FromText(Text.Start(Text.From(_),10)), type date}}),
				    Typed = Table.TransformColumnTypes(Dated, {{"TrendAgentPresent", Int64.Type}})
				in
				    Typed
