table LegacyAvMigration

	column LegacyId
		dataType: string
		sourceColumn: LegacyId

	column LegacyProduct
		dataType: string
		sourceColumn: LegacyProduct

	column LegacyVendor
		dataType: string
		sourceColumn: LegacyVendor

	column LegacyDeviceName
		dataType: string
		sourceColumn: LegacyDeviceName

	column DefenderDeviceName
		dataType: string
		sourceColumn: DefenderDeviceName

	column DeviceId
		dataType: string
		sourceColumn: DeviceId

	column MatchType
		dataType: string
		sourceColumn: MatchType

	column MatchScore
		dataType: int64
		sourceColumn: MatchScore
		formatString: 0

	column OnboardingStatus
		dataType: string
		sourceColumn: OnboardingStatus

	column OSPlatform
		dataType: string
		sourceColumn: OSPlatform

	column OSVersion
		dataType: string
		sourceColumn: OSVersion

	column MigrationStatus
		dataType: string
		sourceColumn: MigrationStatus

	measure 'Legacy Source Devices' = COUNTROWS(LegacyAvMigration) + 0
		formatString: 0

	measure 'Legacy Migrated' = CALCULATE(COUNTROWS(LegacyAvMigration), LegacyAvMigration[MigrationStatus] = "Migrated to Defender") + 0
		formatString: 0

	measure 'Legacy Onboarding Pending' = CALCULATE(COUNTROWS(LegacyAvMigration), LegacyAvMigration[MigrationStatus] = "Matched - not onboarded")
		formatString: 0

	measure 'Legacy Not In Defender' = CALCULATE(COUNTROWS(LegacyAvMigration), LegacyAvMigration[MigrationStatus] = "Not found in Defender") + 0
		formatString: 0

	measure 'Legacy Migration %' = DIVIDE([Legacy Migrated], [Legacy Source Devices], 0)
		formatString: 0.0%

	/// Number of distinct third-party AV/EDR products still represented in the source list.
	measure 'Legacy Products In Scope' = DISTINCTCOUNT(LegacyAvMigration[LegacyProduct]) + 0
		formatString: 0

	/// Products that still have at least one device not yet migrated to Defender.
	measure 'Legacy Products Not Complete' =
			VAR NotDone =
			    FILTER(
			        VALUES(LegacyAvMigration[LegacyProduct]),
			        CALCULATE(COUNTROWS(LegacyAvMigration), LegacyAvMigration[MigrationStatus] <> "Migrated to Defender") > 0
			    )
			RETURN COUNTROWS(NotDone)
		formatString: 0

	/// Migration % for the single product with the LOWEST completion, so a laggard tool is visible
	/// even when the overall percentage looks healthy.
	measure 'Legacy Slowest Product %' =
			VAR ByProduct =
			    ADDCOLUMNS(
			        VALUES(LegacyAvMigration[LegacyProduct]),
			        "@Pct", DIVIDE(
			            CALCULATE(COUNTROWS(LegacyAvMigration), LegacyAvMigration[MigrationStatus] = "Migrated to Defender"),
			            CALCULATE(COUNTROWS(LegacyAvMigration))
			        )
			    )
			RETURN MINX(ByProduct, [@Pct])
		formatString: 0.0%

	/// Name of the product with the lowest migration completion (pairs with the measure above).
	measure 'Legacy Slowest Product' =
			VAR ByProduct =
			    ADDCOLUMNS(
			        VALUES(LegacyAvMigration[LegacyProduct]),
			        "@Pct", DIVIDE(
			            CALCULATE(COUNTROWS(LegacyAvMigration), LegacyAvMigration[MigrationStatus] = "Migrated to Defender"),
			            CALCULATE(COUNTROWS(LegacyAvMigration))
			        )
			    )
			VAR Worst = MINX(ByProduct, [@Pct])
			RETURN
			    IF(
			        ISBLANK(Worst),
			        BLANK(),
			        CONCATENATEX(
			            FILTER(ByProduct, [@Pct] = Worst),
			            LegacyAvMigration[LegacyProduct],
			            ", "
			        )
			    )
		formatString: @

	partition LegacyAvMigration = m
		mode: import
		source =
				let
				    // ------------------------------------------------------------------
				    // Legacy AV/EDR -> Defender migration mapping. Materialised at DEPLOY
				    // time by the deploy script (or Import-LegacyAvInventory.ps1): each
				    // third-party AV/EDR device export supplied via -LegacyCsv is matched
				    // against the current Defender device inventory (the same paged
				    // GET /api/machines export endpoint that feeds DeviceHealth, called with
				    // an app-only token), and the result is embedded below as a base64-encoded
				    // JSON literal (__LEGACYMIGRATION_SEED_B64__), regenerated on every
				    // (re)deploy.
				    //
				    // MULTI-VENDOR: every row carries its own LegacyProduct and LegacyVendor,
				    // so a customer migrating off several tools at once (for example Trend
				    // Micro Apex One AND CrowdStrike Falcon) can slice migration progress by
				    // product. The same hostname present in two products is two rows on
				    // purpose - they are two separate agents to remove.
				    //
				    // Why materialised at deploy rather than an interactive/Power Query upload:
				    // the model refreshes in the Power BI service via a Service Principal with
				    // no on-premises data gateway, so a local-file source could never refresh
				    // in the service. Seeding the mapping at deploy is the durable, gateway-free
				    // path - identical to the DeploymentTrend and AV-posture seeds.
				    //
				    // When no -LegacyCsv is supplied the seed is an empty array, so the table
				    // exists (its columns and measures resolve) but carries no rows.
				    // ------------------------------------------------------------------
				    SeedB64 = "__LEGACYMIGRATION_SEED_B64__",
				    Results = Json.Document(Binary.FromText(SeedB64, BinaryEncoding.Base64)),
				    AsTable = Table.FromRecords(Results, {"LegacyId", "LegacyProduct", "LegacyVendor", "LegacyDeviceName", "DefenderDeviceName", "DeviceId", "MatchType", "MatchScore", "OnboardingStatus", "OSPlatform", "OSVersion", "MigrationStatus"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(AsTable, {{"MatchScore", Int64.Type}})
				in
				    Typed
